### PR TITLE
Create ic-disable-inputs attribute

### PR DESCRIPTION
**Pull request by zodman**
On a request we closestAttrValue('ic-disable-inputs') of the element submitting. If it is true, we search for all inputs below that element and disable them.

Then you could put ic-disable-inputs on a form and have it disable all input elements below, put it on a single input, etc.

### CODE REVIEW

**Comment by zodman** [comment]
some can check this?¿

**Comment by zodman** [comment]
@chg20  can check it plz!

**Comment by chg20** [comment]
I'm a little worried that this would cause a big change in behavior.  Maybe it would be OK if the element type were verified?

**Comment by zodman** [comment]
@chg20 done!

**Comment by zodman** [comment]
@chg20  can you take a look! thanks in advance.

**Comment by zodman** [comment]
ping!

**Comment by chg20** [comment]
Can I ask that this be reworked and expanded a bit?

I think the right behavior is to add a new attribute: ic-disable-inputs="true"

On a request we closestAttrValue('ic-disable-inputs') of the element submitting.  If it is true, we search for all inputs below that element and disable them.

Then you could put ic-disable-inputs on a form and have it disable all input elements below, put it on a single input, etc.

Does this sound reasonable?

I also would like a test for this if possible.

**Comment by zodman** [comment]
for the hack October https://hacktoberfest.digitalocean.com/ i will working with this!

**Comment by chg20** [comment]
awesome 👍

**Comment by chg20** [comment]
@zodman I'm planning on doing a realase at the end of hacktober, let me know if you need any help or encouragement getting this done.  I think it is a good feature!

**Comment by chg20** [comment]
OK!  I will integrate this, but it needs docs!

**Comment by 1cg** [comment]
@zodman very sorry but I'm not accepting new functionality only bug fixes for intercooler

**Pull request closed without merging**
